In [46]:
from google.colab import drive
drive.mount('/content.drive')

Mounted at /content.drive

In [47]:
#titanic 데이터 불러오기
import pandas as pd

base_path="/content.drive/MyDrive/titanic"

train = pd.read_csv(base_path + "/train.csv")
test = pd.read_csv(base_path + "/test.csv")
submission = pd.read_csv(base_path + "/gender_submission.csv")

In [48]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [49]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Data Preprocessing

### 1. 결측치 처리
### 2. feature selection(분석에 사용하지 않을 column 제거)

In [50]:
#titanic data에서 missing value를 찾아보자
train[train.isnull().any(axis=1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [51]:
#Embarked column이 NaN이 row를 찾기

train[train.Embarked.isnull()] #2개 나옴

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [52]:
train.Embarked.value_counts() #-> # 방법 1: 대부분이 S이므로 "s"로 변환

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [53]:
#train[train["Sex"] == 'female']
#train.loc[train.Pclass == 1 & train.Sex =='female']
train.loc[(train.Pclass == 1) & (train.Sex == 'female'),"Embarked"].value_counts()
# --> "S로 변경"

S    48
C    43
Q     1
Name: Embarked, dtype: int64

In [54]:
# S로 채우기

train.loc[train.Embarked.isnull(),'Embarked']="S"
train.loc[(train.Pclass == 1) & (train.Sex == 'female'),"Embarked"].value_counts()

S    50
C    43
Q     1
Name: Embarked, dtype: int64

In [55]:
train.info() #embarked non-null 확인가능

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [56]:
# missing value를 handling합니다.
# column을 지울까요 / 채울까요?
# drop할 columns들을 골라보자 -> 생존율이랑 관계 없을 것 같은거
# PassengerID, Name, Ticket, Cabin,

train= train.drop(columns=["PassengerId","Name","Ticket","Cabin"])
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

In [57]:
# "Age" column 채우기

train = train.fillna(train.Age.mean())
train.info() # age non-null 확인 완료

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB

## Feature Engineering

### 1. Categorical feature encoding
### 2. Normalization

In [58]:
# categorical feature --> one-hot Encoding, Ordinal Encoding

#1. ordinal Encoding --> ordinal feature를 변환할 때 쓰임. e.g. 학력, 선호도
#2. one-hot Encoding --> nominalfeature를 변환할 때 쓰임. e.g.성별,부서,출신학교...

pd.get_dummies(train, columns=["Sex","Embarked"]) #원핫인코딩, sex/Embarked로
# female 0, male 1/  CQS 중 탑승한 곳은 1, 아닌 곳은 0

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.000000,1,0,7.2500,0,1,0,0,1
1,1,1,38.000000,1,0,71.2833,1,0,1,0,0
2,1,3,26.000000,0,0,7.9250,1,0,0,0,1
3,1,1,35.000000,1,0,53.1000,1,0,0,0,1
4,0,3,35.000000,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,0,1,0,0,1
887,1,1,19.000000,0,0,30.0000,1,0,0,0,1
888,0,3,29.699118,1,2,23.4500,1,0,0,0,1
889,1,1,26.000000,0,0,30.0000,0,1,1,0,0
890,0,3,32.000000,0,0,7.7500,0,1,0,1,0

In [59]:
train_OHE= pd.get_dummies(train, columns=["Sex","Embarked"])
train_OHE

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.000000,1,0,7.2500,0,1,0,0,1
1,1,1,38.000000,1,0,71.2833,1,0,1,0,0
2,1,3,26.000000,0,0,7.9250,1,0,0,0,1
3,1,1,35.000000,1,0,53.1000,1,0,0,0,1
4,0,3,35.000000,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,0,1,0,0,1
887,1,1,19.000000,0,0,30.0000,1,0,0,0,1
888,0,3,29.699118,1,2,23.4500,1,0,0,0,1
889,1,1,26.000000,0,0,30.0000,0,1,1,0,0
890,0,3,32.000000,0,0,7.7500,0,1,0,1,0

In [60]:
# Normalization --> Min-Max scaling
# survived 0,1로 구분되어진 라벨링인데 이걸 정규화 하면 안되지 그래서 빼주자
X= train_OHE.drop(columns = "Survived") #input matrix
y= train_OHE.Survived #target vector
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
# scaler.fit()
# scaler.transform()
#X_scaled =scaler.fit_transform(X) # 한 번에 가능
temp = scaler.fit_transform(X.loc[:,["Age","Fare"]])
X["Age"]=temp[:,0]
X["Fare"] = temp[:,1]
X

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,0.271174,1,0,0.014151,0,1,0,0,1
1,1,0.472229,1,0,0.139136,1,0,1,0,0
2,3,0.321438,0,0,0.015469,1,0,0,0,1
3,1,0.434531,1,0,0.103644,1,0,0,0,1
4,3,0.434531,0,0,0.015713,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
886,2,0.334004,0,0,0.025374,0,1,0,0,1
887,1,0.233476,0,0,0.058556,1,0,0,0,1
888,3,0.367921,1,2,0.045771,1,0,0,0,1
889,1,0.321438,0,0,0.058556,0,1,1,0,0
890,3,0.396833,0,0,0.015127,0,1,0,1,0

## Training

In [61]:
# sklearn에서 배웠던 분류 모델들을 불러와 보자.
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

#평가지표
from sklearn.metrics import accuracy_score

In [62]:
clf = SGDClassifier()
clf2 = LogisticRegression()
clf3 = DecisionTreeClassifier()
clf4= RandomForestClassifier()

clf.fit(X,y)
clf2.fit(X,y)
clf3.fit(X,y)
clf4.fit(X,y)

pred=clf.predict(X) # train에 대한 학습 결과
pred2=clf2.predict(X)
pred3=clf3.predict(X)
pred4=clf4.predict(X)

In [63]:
print(" 1. Linear Classifier, Accuracy for training : %.4f" % accuracy_score(y,pred))
print(" 2. Logistic Regression, Accuracy for training : %.4f" % accuracy_score(y,pred2))
print(" 3. Decision Tree, Accuracy for training : %.4f" % accuracy_score(y,pred3))
print(" 4. RandomForest , Accuracy for training : %.4f" % accuracy_score(y,pred4))

 1. Linear Classifier, Accuracy for training : 0.7935
 2. Logistic Regression, Accuracy for training : 0.8013
 3. Decision Tree, Accuracy for training : 0.9820
 4. RandomForest , Accuracy for training : 0.9820

## Test(Predict)

In [64]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [65]:
# test data에 같은 feature engineering을 적용해줍니다.

#imputation (대체)
test = test.drop(columns=["PassengerId","Name","Ticket","Cabin"])
test = test.fillna(train.Age.mean()) # test에 대해서 뭘 하는게 아니라 모든 처리는 train에서 끝났음.

#categoricalfeature encoding
test_OHE = pd.get_dummies(data = test, columns =["Sex","Embarked"])

#Normalization
temp = scaler.transform(test_OHE.loc[:, ["Age","Fare"]])
test_OHE.Age = temp[:,0]
test_OHE.Fare = temp[:,1]

test_OHE

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,0.428248,0,0,0.015282,0,1,0,1,0
1,3,0.585323,1,0,0.013663,1,0,0,0,1
2,2,0.773813,0,0,0.018909,0,1,0,1,0
3,3,0.334004,0,0,0.016908,0,1,0,0,1
4,3,0.271174,1,1,0.023984,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
413,3,0.367921,0,0,0.015713,0,1,0,0,1
414,1,0.484795,0,0,0.212559,1,0,1,0,0
415,3,0.478512,0,0,0.014151,0,1,0,0,1
416,3,0.367921,0,0,0.015713,0,1,0,0,1
417,3,0.367921,1,1,0.043640,0,1,1,0,0

In [66]:
## prediction
## 여기선 fit을 할 수 가 없음 왜? y가 없으니깐
result=clf.predict(test_OHE)
result2=clf2.predict(test_OHE)
result3=clf3.predict(test_OHE)
result4=clf4.predict(test_OHE)

In [68]:
# 결과 파일인 submission.csv 생성
submission["Survived"]=result4
submission

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         1
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [69]:
submission.to_csv("submission.csv",index=False) # 저장